# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/P780_ROW/setup-makefiles.sh

PRODUCT_COPY_FILES += \
 vendor/lenovo/P780_ROW/proprietary/etc/agps_profiles_conf.xml:system/etc/agps_profiles_conf.xml \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628_patch_e2_1_hdr.bin:system/etc/firmware/mt6628_patch_e2_1_hdr.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v5_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v5_patch.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v2_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v2_patch.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v4_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v4_patch.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v3_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v3_patch.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_rom.bin:system/etc/firmware/mt6628/mt6628_fm_rom.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v1_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v1_patch.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/modem_1_3g_n.img:system/etc/firmware/modem_1_3g_n.img \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628_ant_m1.cfg:system/etc/firmware/mt6628_ant_m1.cfg \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628_patch_e2_0_hdr.bin:system/etc/firmware/mt6628_patch_e2_0_hdr.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/WIFI_RAM_CODE_MT6630:system/etc/firmware/WIFI_RAM_CODE_MT6630 \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/WIFI_RAM_CODE_SOC:system/etc/firmware/WIFI_RAM_CODE_SOC \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/catcher_filter_1_3g_n.bin:system/etc/firmware/catcher_filter_1_3g_n.bin \
 vendor/lenovo/P780_ROW/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
 vendor/lenovo/P780_ROW/proprietary/etc/mddb/BPLGUInfoCustomAppSrcP_MT6589_S00_MOLY_WR8_W1248_MD_WG_MP_V44_P9_1_3g_n:system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6589_S00_MOLY_WR8_W1248_MD_WG_MP_V44_P9_1_3g_n \
 vendor/lenovo/P780_ROW/proprietary/etc/throttle.sh:system/etc/throttle.sh \
 vendor/lenovo/P780_ROW/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
 vendor/lenovo/P780_ROW/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
 vendor/lenovo/P780_ROW/proprietary/etc/gps.conf:system/etc/gps.conf \
 vendor/lenovo/P780_ROW/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
 vendor/lenovo/P780_ROW/proprietary/etc/.tp/thermal.off.conf:system/etc/.tp/thermal.off.conf \
 vendor/lenovo/P780_ROW/proprietary/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
 vendor/lenovo/P780_ROW/proprietary/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \
 vendor/lenovo/P780_ROW/proprietary/bin/drvbd:system/bin/drvbd \
 vendor/lenovo/P780_ROW/proprietary/bin/thermal:system/bin/thermal \
 vendor/lenovo/P780_ROW/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
 vendor/lenovo/P780_ROW/proprietary/bin/bmm050d:system/bin/bmm050d \
 vendor/lenovo/P780_ROW/proprietary/bin/bmm056d:system/bin/bmm056d \
 vendor/lenovo/P780_ROW/proprietary/bin/thermal_manager:system/bin/thermal_manager \
 vendor/lenovo/P780_ROW/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
 vendor/lenovo/P780_ROW/proprietary/bin/6620_launcher:system/bin/6620_launcher \
 vendor/lenovo/P780_ROW/proprietary/bin/akmd8975:system/bin/akmd8975 \
 vendor/lenovo/P780_ROW/proprietary/bin/muxreport:system/bin/muxreport \
 vendor/lenovo/P780_ROW/proprietary/bin/permission_check:system/bin/permission_check \
 vendor/lenovo/P780_ROW/proprietary/bin/ami304d:system/bin/ami304d \
 vendor/lenovo/P780_ROW/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
 vendor/lenovo/P780_ROW/proprietary/bin/wmt_loader:system/bin/wmt_loader \
 vendor/lenovo/P780_ROW/proprietary/bin/rild:system/bin/rild \
 vendor/lenovo/P780_ROW/proprietary/bin/orientationd:system/bin/orientationd \
 vendor/lenovo/P780_ROW/proprietary/bin/pppd:system/bin/pppd \
 vendor/lenovo/P780_ROW/proprietary/bin/akmd8963:system/bin/akmd8963 \
 vendor/lenovo/P780_ROW/proprietary/bin/wlan_loader:system/bin/wlan_loader \
 vendor/lenovo/P780_ROW/proprietary/bin/rildmd2:system/bin/rildmd2 \
 vendor/lenovo/P780_ROW/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
 vendor/lenovo/P780_ROW/proprietary/bin/msensord:system/bin/msensord \
 vendor/lenovo/P780_ROW/proprietary/bin/memsicd:system/bin/memsicd \
 vendor/lenovo/P780_ROW/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
 vendor/lenovo/P780_ROW/proprietary/bin/pppd_dt:system/bin/pppd_dt \
 vendor/lenovo/P780_ROW/proprietary/bin/geomagneticd:system/bin/geomagneticd \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libion.so:system/lib/libion.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
 vendor/lenovo/P780_ROW/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
 vendor/lenovo/P780_ROW/proprietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libnvram.so:system/lib/libnvram.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
 vendor/lenovo/P780_ROW/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
 vendor/lenovo/P780_ROW/proprietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libbluetoothdrv.so:system/lib/libbluetoothdrv.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libdpframework_os.so:system/lib/libdpframework_os.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libbwc.so:system/lib/libbwc.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libhwm.so:system/lib/libhwm.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libbessound_mtk.so:system/lib/libbessound_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
 vendor/lenovo/P780_ROW/proprietary/lib/lib3a.so:system/lib/lib3a.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmpo.so:system/lib/libmpo.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libssladp.so:system/lib/libssladp.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libdpframework_plat.so:system/lib/libdpframework_plat.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libimageio.so:system/lib/libimageio.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libaed.so:system/lib/libaed.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libm4u.so:system/lib/libm4u.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/hwcomposer.mt6589.so:system/lib/hw/hwcomposer.mt6589.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/audio.primary.mt6589.so:system/lib/hw/audio.primary.mt6589.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
 vendor/lenovo/P780_ROW/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
 vendor/lenovo/P780_ROW/proprietary/xbin/libmnlp_mt6628:system/xbin/libmnlp_mt6628 \
 vendor/lenovo/P780_ROW/proprietary/xbin/mnld:system/xbin/mnld \
 vendor/lenovo/P780_ROW/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
 vendor/lenovo/P780_ROW/proprietary/vendor/bin/rc.fac:system/vendor/bin/rc.fac \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/libBLPP.so:system/vendor/lib/libBLPP.so \
 vendor/lenovo/P780_ROW/proprietary/vendor/lib/hw/gralloc.mt6589.so:system/vendor/lib/hw/gralloc.mt6589.so
# vendor/lenovo/P780_ROW/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so
PRODUCT_COPY_FILES += \
  vendor/lenovo/P780_ROW/proprietary/lib/hw/audio.primary.mt6589.so:system/lib/hw/audio.primary.mt6589.so \
